//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indextimetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int ID { get; set; }
        public string CA_HỌC { get; set; }
        public string Thứ_2 { get; set; }
        public string Thứ_3 { get; set; }
        public string Thứ_4 { get; set; }
        public string Thứ_5 { get; set; }
        public string Thứ_6 { get; set; }
        public string Thứ_7 { get; set; }
    }
}
